### ISSUE TITLE
Supplementary Figures and Tables

### ISSUE THREAD

**Issue by kescobo** [Klepac-Ceraj-Lab/Resonance#100]
## Related to figure 1

- [x] Samples histogram by age `S1`
- [x] PCoAs of taxonomic profiles colored by Bacteroidetes, Firmicutes, _P. copri_ `S2`
- [x] covid19 / cogscores `S3`

## Related to figure 2

- [ ] anything?

## Related to figure 3

- [x] Pareto plots for bugs `S4` @Hugemiler #153 

## Related to figure 4

- [x] Full-dataset heatmap @Hugemiler Figure `S5` #153 
- [x] Same as C, but larger, with xticks @kescobo `S6` #157 
- [ ] Pareto plots for bugs / average @Hugemiler `S7` #153 
- [ ] Pareto plots for bugs / individual segements??

**Comment by kescobo** [comment]
Are we missing any supplementary figures? @vanjakle @Hugemiler
