### ISSUE TITLE
Revision Checklist

### ISSUE THREAD

**Issue by kescobo** [Klepac-Ceraj-Lab/Resonance#171]
## To dos left after :baby:  for @Hugemiler or @vanjakle 

- [x] Figure out what's going on with FSEAs (see slack)
- [x] Fix figure label aligments (eg 2C, 3A) #183 
- [x] Review / rewrite subscores for figure 2
- [x] Write subscore results for Figure 4 - may need to change some of the species that are displayed in 4C
- [x] #184
- [x] #185
- [x] #186
- [x] #187
- [x] Add tables for the subscores figures of merit #191 
- [x] #179 
- [x] #180 
- [x] #181 
- [x] Wrap up R2R with new additions

## Checks

* completed in #197 *

- [x] Update numbers for any models / stats in text
- [x] Remove refs to bugs that aren’t significant
- [x] Add refs to bugs that are newly significant
- [x] Update figure / panel references (eg figure 4A -> 5B or whatever)

--- 

### Compilation

I'm using the LaTeX workshop extension of VS code. You'll need `texlive-full` installed on your system. I'm using the lualatex recipe, but I think others should work too

### Diff

Use `latexdiff` from inside the manuscript directory:

```
latexdiff submission.tex main.tex > diff.tex
```

The initial diff will probably not compile. If you're using LaTeX workshop, the file minimap should show up red where the problem happened (often in the tables). Try to fix the errors; sometimes you just have to delete the line - it doesn't need to be immaculate - and then recompile. DO NOT TRY TO LEARN THE DIFF SYNTAX. Rinse, repeat until it finishes.

**Comment by kescobo** [comment]
@Hugemiler @vanjakle I think this list is still germaine. I just merged #170, which has rewrites for fig 1 and some partial rewrites for fig 2. I propose separate rewrite PRs for each figure - I'll get started on figure 1 and 2, @Hugemiler can you start working on 3 and 4?
